version: 2
jobs:
  test:
    working_directory: ~/domain_check_app
    docker:
      - image: circleci/python:3.7.0-stretch
    steps:
      - checkout
      - run:
          name: Set up environment
          command: |
            sudo pip install pipenv==2018.11.26
            pipenv install
      - run:
          name: Run Tests
          command: |
            pipenv install coverage coveralls
            cd src/core
            pipenv run coverage run --source='.' manage.py test
            pipenv run coverage report --rcfile=../../.coveragerc
            pipenv run coverage html --rcfile=../../.coveragerc
            export COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
            pipenv run coveralls --rcfile=../../.coveragerc
workflows:
  version: 2
  test-application:
    jobs:
      - test